---
name: Global workflow example

on: pull_request

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: SCE validator
      uses: Devx-USC/sce-validator@main

