---
name: SCE validator global workflow
on: pull_request

jobs:
  sce-validator:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: SCE validator
      uses: Devx-USC/sce-validator@main
      with:
        test_sa_key: ${{ secrets.GCP_TEST_SA_KEY }}
        trigger: ${{ github.event_name }}
