---
name: Global workflow example

on: pull_request

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Debug github workspace
      run: ls -lah ${{ github.workspace }}

    - name: SCE validator
      uses: Devx-USC/sce-validator@main
      with:
        test_sa_key: ${{ secrets.GCP_TEST_SA_KEY }}
  