name: Handle webhook event

on:
  push:

jobs:
  process-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract event payload
      id: extract_payload
      run: echo "test"
