name: Handle webhook event

on:
  repository_dispatch:
    types: [techdocs_update]

jobs:
  process-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract event payload
      id: extract_payload
      run: echo "::set-output name=payload::${{ github.event.client_payload }}"
